### ISSUE TITLE
How can I use web APIs?

### ISSUE THREAD

**Issue by solomatov** [google/j2cl#15]
Can I use elemental2 jars from maven for it?

**Comment by rluble** [comment]
You should be able to use them. Either from maven of from the elemental2 github repo. Here is a link to the [instructions for projects using bazel](https://github.com/google/elemental2#bazel-dependencies).

**Comment by gkdn** [comment]
No it doesn't work yet; needs porting. We have a TODO item for it in spreadsheet.

**Comment by solomatov** [comment]
@gkdn Is this spreadsheet public? Can I take a look at it?

**Comment by rluble** [comment]
Yeah, @gkdn is right. The spreadsheet is of our internal TODOs but the ones related to open-source J2CL are
- update elemental2 to work in J2cl (which involves also involves our internal export tooling)
- implement an external version of j2cl_test.
- make sure all tests are passing in the external repo.

If you feel brave and really want to use elemental2, I guess you could hack a version to play with it by modifying the bzl and BUILD files in a similar way to jsinterop-base (commit google/jsinterop-base@503e4422a). YMMV.

Sorry for the confusion.

**Comment by jDramaix** [comment]
You can also use the Maven jar and use a j2cl_import bazel rule.

**Comment by solomatov** [comment]
And what about this comment there?

>Should only be used for importing annotation byte code, otherwise may result
> in hard to debug errors!

Will it really work?

**Comment by niloc132** [comment]
@jDramaix I don't think the maven jar works, since it expects jsinterop-base to work, and at least those published jars don't have the expected js required (goog.requires for properties, native.js for j2cl's impl of JSNI methods)

As a possible workaround, we've opened up our maven repo for external use - we forked jsinterop-base and elemental2 a while back to get them working under j2cl. Downside: these have not quite consistent with the regular published jars and haven't been looked at in a while, so do not match the JsArray.getAny (among a few other calls). To use (at least from maven, probably easier in bazel), be sure to exclude any other copies of elemental2, jsinterop-base.

Repo is at https://repo.vertispan.com/j2cl, look for the com.vertispan.jsinterop and .elemental2 dependencies. These are working when used in https://github.com/vertispan/connected/tree/j2cl and https://github.com/DominoKit/dominodo/tree/j2cl/ (will be updated soon).

**Comment by solomatov** [comment]
I tried using them but wasn't able to set it up. Elemental2 isn't compatible with j2cl in one bazel project: https://github.com/google/elemental2/issues/68

**Comment by solomatov** [comment]
Are there any updates on this?

**Comment by gkdn** [comment]
@jDramaix , could you provide an update on the progress?

**Comment by jDramaix** [comment]
It's nearly done. The only problem is if you use bazelbuild/rules_closure. Those rules embed their own version of extern files that are not necessarily synced with version used by elemental. We need to modify those rule not to add their externs by default.

**Comment by solomatov** [comment]
Are there any updates? I would be glad to experiment with J2CL and libraries.

**Comment by realityforge** [comment]
Indeed. This seems to be the last little hurdle for me too ;)

**Comment by solomatov** [comment]
Are there any news? I would love to try j2cl, but we use bazel, and I don't want to have maven setup.

**Comment by jDramaix** [comment]
We plan to release a version of Elemental2 working with Bazel setup tomorrow.

**Comment by jDramaix** [comment]
Please follow the instructions in the elemental2 README: https://github.com/google/elemental2#bazel-dependencies
